# This file is auto-generated by `../tools/generate-inherit.py`. Edits may be lost.

from collections import namedtuple

try:
    from odoo.tools.misc import frozendict
    from odoo.tools.parse_version import parse_version
except ImportError:
    from openerp.tools.parse_version import parse_version

    try:
        from openerp.tools.misc import frozendict
    except ImportError:
        # frozendict only appears with new api in 8.0
        frozendict = dict

Inherit = namedtuple("Inherit", "model born dead")  # NOTE: dead is non-inclusive

inheritance_data = frozendict(
    {
        "account.abstract.payment": [
            Inherit(model="account.payment", born=parse_version("9.0"), dead=parse_version("saas~12.3")),
            Inherit(model="account.register.payments", born=parse_version("9.0"), dead=parse_version("saas~12.3")),
        ],
        "account.aged.partner": [
            Inherit(model="account.aged.payable", born=parse_version("9.saas~11"), dead=None),
            Inherit(model="account.aged.receivable", born=parse_version("9.saas~11"), dead=None),
        ],
        "account.analytic.account": [
            Inherit(model="project.project", born=parse_version("7.0"), dead=parse_version("saas~11.3")),
            Inherit(model="sale.subscription", born=parse_version("9.0"), dead=parse_version("10.saas~17")),
        ],
        "account.analytic.line": [
            Inherit(model="hr.analytic.timesheet", born=parse_version("7.0"), dead=parse_version("9.0"))
        ],
        "account.coa.report": [Inherit(model="l10n_mx.trial.report", born=parse_version("10.saas~14"), dead=None)],
        "account.common.account.report": [
            Inherit(model="account.balance.report", born=parse_version("7.0"), dead=parse_version("saas~11.5")),
            Inherit(model="account.report.general.ledger", born=parse_version("7.0"), dead=parse_version("saas~11.5")),
        ],
        "account.common.journal.report": [
            Inherit(model="account.central.journal", born=parse_version("7.0"), dead=parse_version("9.0")),
            Inherit(model="account.general.journal", born=parse_version("7.0"), dead=parse_version("9.0")),
            Inherit(model="account.print.journal", born=parse_version("7.0"), dead=None),
        ],
        "account.common.partner.report": [
            Inherit(model="account.aged.trial.balance", born=parse_version("7.0"), dead=parse_version("saas~11.5")),
            Inherit(model="account.partner.balance", born=parse_version("7.0"), dead=parse_version("9.0")),
            Inherit(model="account.partner.ledger", born=parse_version("7.0"), dead=parse_version("9.0")),
            Inherit(model="account.report.partner.ledger", born=parse_version("9.0"), dead=parse_version("saas~11.5")),
        ],
        "account.common.report": [
            Inherit(model="account.common.account.report", born=parse_version("7.0"), dead=parse_version("saas~11.5")),
            Inherit(model="account.common.journal.report", born=parse_version("7.0"), dead=None),
            Inherit(model="account.common.partner.report", born=parse_version("7.0"), dead=parse_version("saas~11.5")),
            Inherit(model="account.tax.report", born=parse_version("10.saas~18"), dead=parse_version("saas~11.5")),
            Inherit(model="account.vat.declaration", born=parse_version("7.0"), dead=parse_version("9.0")),
            Inherit(model="accounting.report", born=parse_version("7.0"), dead=parse_version("saas~11.5")),
        ],
        "account.followup.report": [
            Inherit(
                model="account.followup.report.all", born=parse_version("10.saas~14"), dead=parse_version("saas~11.3")
            )
        ],
        "account.general.ledger": [
            Inherit(model="account.coa.report", born=parse_version("9.0"), dead=parse_version("saas~12.4")),
            Inherit(model="l10n.sg.reports.iaf", born=parse_version("saas~11.2"), dead=None),
            Inherit(model="l10n_us_reports.check.register", born=parse_version("10.saas~17"), dead=None),
        ],
        "account.journal": [
            Inherit(model="account.bank.statement.import.journal.creation", born=parse_version("9.0"), dead=None)
        ],
        "account.move": [
            Inherit(model="account.bank.statement.line", born=parse_version("saas~13.4"), dead=None),
            Inherit(model="account.payment", born=parse_version("saas~13.4"), dead=None),
        ],
        "account.report": [
            Inherit(model="account.aged.partner", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="account.analytic.report", born=parse_version("saas~11.2"), dead=None),
            Inherit(model="account.assets.report", born=parse_version("saas~12.3"), dead=None),
            Inherit(model="account.bank.reconciliation.report", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="account.cash.flow.report", born=parse_version("11.0"), dead=None),
            Inherit(model="account.coa.report", born=parse_version("saas~12.4"), dead=None),
            Inherit(model="account.consolidated.journal", born=parse_version("10.saas~15"), dead=None),
            Inherit(model="account.consolidation.trial_balance_report", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="account.eightcolumns.report.cl", born=parse_version("saas~12.2"), dead=None),
            Inherit(model="account.financial.html.report", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="account.followup.report", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="account.general.ledger", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="account.generic.tax.report", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="account.intrastat.report", born=parse_version("saas~11.5"), dead=None),
            Inherit(model="account.multicurrency.revaluation.report", born=parse_version("saas~13.3"), dead=None),
            Inherit(model="account.partner.ledger", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="account.sales.report", born=parse_version("saas~11.5"), dead=None),
            Inherit(model="l10n.au.tax.report", born=parse_version("saas~13.4"), dead=None),
            Inherit(model="l10n.be.report.partner.vat.intra", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="l10n.be.report.partner.vat.listing", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="l10n.de.report.partner.vat.intra", born=parse_version("10.saas~18"), dead=None),
            Inherit(model="l10n.in.report.account", born=parse_version("saas~12.1"), dead=None),
            Inherit(model="l10n.lu.report.partner.vat.intra", born=parse_version("13.0"), dead=None),
            Inherit(model="l10n.nl.report.intrastat", born=parse_version("10.saas~18"), dead=None),
            Inherit(model="l10n_ar.vat.book", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="l10n_co_reports.certification_report", born=parse_version("10.saas~18"), dead=None),
            Inherit(model="l10n_mx.account.diot", born=parse_version("10.saas~14"), dead=None),
        ],
        "account.report.analytic.manager": [
            Inherit(
                model="account.report.context.common", born=parse_version("9.saas~11"), dead=parse_version("10.saas~14")
            )
        ],
        "account.report.context.common": [
            Inherit(
                model="account.context.aged.payable", born=parse_version("9.saas~11"), dead=parse_version("10.saas~14")
            ),
            Inherit(
                model="account.context.aged.receivable",
                born=parse_version("9.saas~11"),
                dead=parse_version("10.saas~14"),
            ),
            Inherit(model="account.context.coa", born=parse_version("9.0"), dead=parse_version("10.saas~14")),
            Inherit(
                model="account.context.general.ledger", born=parse_version("9.0"), dead=parse_version("10.saas~14")
            ),
            Inherit(
                model="account.financial.html.report.context",
                born=parse_version("9.0"),
                dead=parse_version("10.saas~14"),
            ),
            Inherit(
                model="account.partner.ledger.context",
                born=parse_version("9.saas~11"),
                dead=parse_version("10.saas~14"),
            ),
            Inherit(
                model="account.report.context.bank.rec", born=parse_version("9.0"), dead=parse_version("10.saas~14")
            ),
            Inherit(
                model="account.report.context.followup", born=parse_version("9.0"), dead=parse_version("10.saas~14")
            ),
            Inherit(model="account.report.context.tax", born=parse_version("9.0"), dead=parse_version("10.saas~14")),
            Inherit(
                model="l10n.be.partner.vat.intra.context", born=parse_version("9.0"), dead=parse_version("10.saas~14")
            ),
            Inherit(
                model="l10n.be.partner.vat.listing.context", born=parse_version("9.0"), dead=parse_version("10.saas~14")
            ),
        ],
        "account.report.footnotes.manager": [
            Inherit(model="account.report.context.common", born=parse_version("9.0"), dead=parse_version("10.saas~14"))
        ],
        "account.report.multicompany.manager": [
            Inherit(model="account.report.context.common", born=parse_version("9.0"), dead=parse_version("10.saas~14"))
        ],
        "barcodes.barcode_events_mixin": [
            Inherit(model="mrp.workorder", born=parse_version("9.saas~13"), dead=parse_version("10.saas~18")),
            Inherit(model="mrp.workorder", born=parse_version("saas~11.4"), dead=None),
            Inherit(model="stock.inventory", born=parse_version("9.0"), dead=parse_version("saas~12.4")),
            Inherit(model="stock.move.line", born=parse_version("10.saas~17"), dead=None),
            Inherit(model="stock.pack.operation", born=parse_version("9.0"), dead=parse_version("10.saas~17")),
            Inherit(model="stock.picking", born=parse_version("9.0"), dead=None),
            Inherit(model="stock.scrap", born=parse_version("9.saas~13"), dead=None),
            Inherit(model="stock_barcode.lot", born=parse_version("10.saas~18"), dead=None),
        ],
        "base.automation": [Inherit(model="sale.subscription.alert", born=parse_version("saas~11.5"), dead=None)],
        "base.config.settings": [
            Inherit(
                model="hr.timesheet.config.settings", born=parse_version("10.saas~15"), dead=parse_version("10.saas~18")
            )
        ],
        "calendar.event": [
            Inherit(model="calendar.todo", born=parse_version("7.0"), dead=parse_version("7.saas~3")),
            Inherit(model="crm.meeting", born=parse_version("7.saas~2"), dead=parse_version("8.0")),
        ],
        "coupon.reward": [Inherit(model="coupon.program", born=parse_version("saas~13.4"), dead=None)],
        "coupon.rule": [Inherit(model="coupon.program", born=parse_version("saas~13.4"), dead=None)],
        "crm.lead": [
            Inherit(model="portal_crm.crm_contact_us", born=parse_version("7.0"), dead=parse_version("7.saas~3"))
        ],
        "crm.lead2opportunity.partner": [
            Inherit(model="crm.lead2opportunity.partner.mass", born=parse_version("7.0"), dead=None)
        ],
        "crm.partner.binding": [
            Inherit(model="crm.lead.convert2task", born=parse_version("10.saas~18"), dead=parse_version("saas~12.1")),
            Inherit(model="crm.lead.convert2ticket", born=parse_version("saas~12.1"), dead=parse_version("saas~13.3")),
            Inherit(model="crm.lead2opportunity.partner", born=parse_version("7.0"), dead=parse_version("saas~13.3")),
            Inherit(
                model="crm.lead2projectissue.wizard", born=parse_version("7.saas~4"), dead=parse_version("10.saas~18")
            ),
            Inherit(model="crm.quotation.partner", born=parse_version("saas~12.3"), dead=parse_version("saas~13.3")),
        ],
        "crm.phonecall2phonecall": [
            Inherit(model="crm.opportunity2phonecall", born=parse_version("7.0"), dead=parse_version("7.saas~5"))
        ],
        "crm.tracking.mixin": [
            Inherit(model="crm.lead.report", born=parse_version("8.0"), dead=parse_version("8.saas~6")),
            Inherit(model="crm.opportunity.report", born=parse_version("8.0"), dead=parse_version("8.saas~6")),
            Inherit(model="mail.mass_mailing", born=parse_version("8.0"), dead=parse_version("8.saas~6")),
            Inherit(model="sale.order", born=parse_version("8.0"), dead=parse_version("8.saas~6")),
        ],
        "documents.mixin": [
            Inherit(model="hr.applicant", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="hr.contract", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="hr.employee", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="hr.job", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="hr.leave", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="hr.payslip", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="product.product", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="product.template", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="project.project", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="project.task", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="sign.request", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="sign.template", born=parse_version("saas~12.5"), dead=None),
        ],
        "email.template": [
            Inherit(model="email_template.preview", born=parse_version("7.0"), dead=parse_version("8.saas~6"))
        ],
        "event.type.ticket": [Inherit(model="event.event.ticket", born=parse_version("saas~13.2"), dead=None)],
        "fetchmail.config.settings": [
            Inherit(model="hr.config.settings", born=parse_version("7.0"), dead=parse_version("9.0")),
            Inherit(model="hr.recruitment.config.settings", born=parse_version("9.0"), dead=parse_version("9.saas~11")),
            Inherit(model="project.config.settings", born=parse_version("7.0"), dead=parse_version("9.0")),
            Inherit(model="sale.config.settings", born=parse_version("7.0"), dead=parse_version("9.saas~11")),
        ],
        "fleet.vehicle.cost": [
            Inherit(model="fleet.vehicle.log.contract", born=parse_version("7.0"), dead=parse_version("saas~13.1")),
            Inherit(model="fleet.vehicle.log.fuel", born=parse_version("7.0"), dead=parse_version("saas~13.1")),
            Inherit(model="fleet.vehicle.log.services", born=parse_version("7.0"), dead=parse_version("saas~13.1")),
        ],
        "format.address.mixin": [
            Inherit(model="crm.lead", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="res.partner", born=parse_version("10.saas~14"), dead=None),
        ],
        "google.calendar.sync": [
            Inherit(model="calendar.event", born=parse_version("saas~13.4"), dead=None),
            Inherit(model="calendar.recurrence", born=parse_version("saas~13.4"), dead=None),
        ],
        "hr.employee.base": [
            Inherit(model="hr.employee", born=parse_version("saas~12.4"), dead=None),
            Inherit(model="hr.employee.public", born=parse_version("saas~12.4"), dead=None),
        ],
        "hr.payroll.281.base.wizard": [
            Inherit(model="hr.payroll.281.10.wizard", born=parse_version("saas~13.3"), dead=None),
            Inherit(model="hr.payroll.281.45.wizard", born=parse_version("saas~13.3"), dead=None),
        ],
        "hr.salary.rule": [
            Inherit(model="hr.payslip.line", born=parse_version("7.0"), dead=parse_version("saas~12.1"))
        ],
        "image.mixin": [
            Inherit(model="forum.forum", born=parse_version("saas~12.4"), dead=None),
            Inherit(model="gamification.badge", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="gamification.karma.rank", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="hr.employee", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="lunch.product", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="lunch.product.category", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="product.image", born=parse_version("saas~12.2"), dead=None),
            Inherit(model="product.public.category", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="product.template", born=parse_version("saas~12.2"), dead=None),
            Inherit(model="res.partner", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="slide.channel", born=parse_version("saas~12.2"), dead=None),
            Inherit(model="slide.slide", born=parse_version("saas~12.2"), dead=None),
        ],
        "ir.actions.actions": [
            Inherit(model="ir.actions.act_url", born=parse_version("7.0"), dead=None),
            Inherit(model="ir.actions.act_window", born=parse_version("7.0"), dead=None),
            Inherit(model="ir.actions.act_window_close", born=parse_version("7.0"), dead=None),
            Inherit(model="ir.actions.client", born=parse_version("7.0"), dead=None),
            Inherit(model="ir.actions.report", born=parse_version("10.saas~17"), dead=None),
            Inherit(model="ir.actions.report.xml", born=parse_version("7.0"), dead=parse_version("10.saas~17")),
            Inherit(model="ir.actions.server", born=parse_version("7.0"), dead=None),
            Inherit(model="ir.actions.wizard", born=parse_version("7.0"), dead=parse_version("7.saas~3")),
        ],
        "ir.actions.server": [
            Inherit(model="base.automation", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="ir.cron", born=parse_version("10.saas~14"), dead=None),
        ],
        "ir.attachment": [Inherit(model="mrp.document", born=parse_version("10.saas~16"), dead=None)],
        "ir.needaction_mixin": [
            Inherit(model="account.asset.asset", born=parse_version("8.saas~6"), dead=parse_version("10.saas~14")),
            Inherit(
                model="account.bank.statement.line", born=parse_version("7.saas~5"), dead=parse_version("10.saas~14")
            ),
            Inherit(model="calendar.event", born=parse_version("7.saas~3"), dead=parse_version("10.saas~14")),
            Inherit(model="crm.case.section", born=parse_version("7.saas~5"), dead=parse_version("8.saas~6")),
            Inherit(model="crm.meeting", born=parse_version("7.saas~2"), dead=parse_version("8.0")),
            Inherit(model="crm.team", born=parse_version("8.saas~6"), dead=parse_version("10.saas~14")),
            Inherit(model="event.event", born=parse_version("7.0"), dead=parse_version("10.saas~14")),
            Inherit(model="event.registration", born=parse_version("7.0"), dead=parse_version("10.saas~14")),
            Inherit(model="event.track", born=parse_version("7.saas~3"), dead=parse_version("10.saas~14")),
            Inherit(model="helpdesk.team", born=parse_version("9.saas~13"), dead=parse_version("10.saas~14")),
            Inherit(model="helpdesk.ticket", born=parse_version("9.saas~13"), dead=parse_version("10.saas~14")),
            Inherit(model="hr.applicant", born=parse_version("7.saas~2"), dead=parse_version("10.saas~14")),
            Inherit(model="hr.contract", born=parse_version("8.saas~6"), dead=parse_version("10.saas~14")),
            Inherit(model="hr.department", born=parse_version("8.saas~6"), dead=parse_version("10.saas~14")),
            Inherit(model="hr.expense", born=parse_version("9.0"), dead=parse_version("10.saas~14")),
            Inherit(model="hr.expense.expense", born=parse_version("8.saas~6"), dead=parse_version("9.0")),
            Inherit(model="hr.expense.sheet", born=parse_version("9.saas~12"), dead=parse_version("10.saas~14")),
            Inherit(model="hr.holidays", born=parse_version("7.0"), dead=parse_version("10.saas~14")),
            Inherit(model="hr.job", born=parse_version("7.saas~4"), dead=parse_version("8.saas~6")),
            Inherit(model="hr_timesheet_sheet.sheet", born=parse_version("8.saas~6"), dead=parse_version("10.saas~14")),
            Inherit(model="mail.message", born=parse_version("7.0"), dead=parse_version("10.saas~14")),
            Inherit(model="mrp.eco", born=parse_version("9.saas~12"), dead=parse_version("10.saas~14")),
            Inherit(model="mrp.production", born=parse_version("7.0"), dead=parse_version("10.saas~14")),
            Inherit(model="procurement.order", born=parse_version("9.0"), dead=parse_version("10.saas~14")),
            Inherit(model="project.issue", born=parse_version("7.saas~2"), dead=parse_version("10.saas~14")),
            Inherit(model="project.project", born=parse_version("7.0"), dead=parse_version("10.saas~14")),
            Inherit(model="project.task", born=parse_version("7.saas~2"), dead=parse_version("10.saas~14")),
            Inherit(model="purchase.order", born=parse_version("7.0"), dead=parse_version("10.saas~14")),
            Inherit(model="purchase.requisition", born=parse_version("7.0"), dead=parse_version("10.saas~14")),
            Inherit(model="sale.order", born=parse_version("7.0"), dead=parse_version("10.saas~14")),
            Inherit(model="survey.survey", born=parse_version("7.saas~4"), dead=parse_version("10.saas~14")),
        ],
        "ir.qweb.field": [
            Inherit(model="ir.qweb.field.barcode", born=parse_version("8.0"), dead=parse_version("9.saas~8")),
            Inherit(model="ir.qweb.field.barcode", born=parse_version("9.saas~9"), dead=None),
            Inherit(model="ir.qweb.field.date", born=parse_version("7.saas~3"), dead=None),
            Inherit(model="ir.qweb.field.datetime", born=parse_version("7.saas~3"), dead=None),
            Inherit(model="ir.qweb.field.duration", born=parse_version("7.saas~3"), dead=None),
            Inherit(model="ir.qweb.field.float", born=parse_version("7.saas~3"), dead=None),
            Inherit(model="ir.qweb.field.float_time", born=parse_version("10.saas~18"), dead=None),
            Inherit(model="ir.qweb.field.html", born=parse_version("7.saas~3"), dead=None),
            Inherit(model="ir.qweb.field.image", born=parse_version("7.saas~3"), dead=None),
            Inherit(model="ir.qweb.field.integer", born=parse_version("9.0"), dead=None),
            Inherit(model="ir.qweb.field.many2many", born=parse_version("saas~11.5"), dead=None),
            Inherit(model="ir.qweb.field.many2one", born=parse_version("7.saas~3"), dead=None),
            Inherit(model="ir.qweb.field.monetary", born=parse_version("7.saas~3"), dead=None),
            Inherit(model="ir.qweb.field.relative", born=parse_version("7.saas~3"), dead=None),
            Inherit(model="ir.qweb.field.selection", born=parse_version("7.saas~3"), dead=None),
            Inherit(model="ir.qweb.field.text", born=parse_version("7.saas~3"), dead=None),
        ],
        "ir.qweb.field.many2one": [
            Inherit(model="ir.qweb.field.contact", born=parse_version("9.saas~11"), dead=None),
            Inherit(model="ir.qweb.field.qweb", born=parse_version("9.saas~11"), dead=None),
        ],
        "ir.qweb.widget": [
            Inherit(model="ir.qweb.widget.monetary", born=parse_version("7.saas~4"), dead=parse_version("9.saas~12"))
        ],
        "ir.ui.view": [Inherit(model="website.page", born=parse_version("10.saas~18"), dead=None)],
        "l10n_co_reports.certification_report": [
            Inherit(model="l10n_co_reports.certification_report.fuente", born=parse_version("10.saas~18"), dead=None),
            Inherit(model="l10n_co_reports.certification_report.ica", born=parse_version("10.saas~18"), dead=None),
            Inherit(model="l10n_co_reports.certification_report.iva", born=parse_version("10.saas~18"), dead=None),
        ],
        "l10n_es_reports.aeat.boe.export.wizard": [
            Inherit(
                model="l10n_es_reports.aeat.boe.mod111and115and303.export.wizard",
                born=parse_version("saas~11.5"),
                dead=None,
            ),
            Inherit(
                model="l10n_es_reports.aeat.boe.mod347and349.export.wizard", born=parse_version("saas~11.5"), dead=None
            ),
        ],
        "l10n_es_reports.aeat.boe.mod111and115and303.export.wizard": [
            Inherit(model="l10n_es_reports.aeat.boe.mod111.export.wizard", born=parse_version("saas~11.5"), dead=None),
            Inherit(model="l10n_es_reports.aeat.boe.mod115.export.wizard", born=parse_version("saas~11.5"), dead=None),
            Inherit(model="l10n_es_reports.aeat.boe.mod303.export.wizard", born=parse_version("saas~11.5"), dead=None),
        ],
        "l10n_es_reports.aeat.boe.mod347and349.export.wizard": [
            Inherit(model="l10n_es_reports.aeat.boe.mod347.export.wizard", born=parse_version("saas~11.5"), dead=None),
            Inherit(model="l10n_es_reports.aeat.boe.mod349.export.wizard", born=parse_version("saas~11.5"), dead=None),
        ],
        "l10n_es_reports.aeat.mod347.manual.partner.data": [
            Inherit(model="l10n_es_reports.aeat.mod347.real.estates.vat", born=parse_version("saas~11.5"), dead=None)
        ],
        "l10n_es_reports.aeat.report.wizard": [
            Inherit(model="l10n_es_reports.mod111.wizard", born=parse_version("10.saas~18"), dead=None),
            Inherit(model="l10n_es_reports.mod115.wizard", born=parse_version("10.saas~18"), dead=None),
            Inherit(model="l10n_es_reports.mod303.wizard", born=parse_version("10.saas~18"), dead=None),
        ],
        "l10n_in.payment.report": [
            Inherit(model="l10n_in.advances.payment.adjustment.report", born=parse_version("saas~12.1"), dead=None),
            Inherit(model="l10n_in.advances.payment.report", born=parse_version("saas~12.1"), dead=None),
        ],
        "l10n_mx.trial.report": [
            Inherit(model="l10n_mx.coa.report", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="l10n_mx.trial.closing.report", born=parse_version("11.0"), dead=None),
        ],
        "l10n_mx_edi.pac.sw.mixin": [
            Inherit(model="account.invoice", born=parse_version("11.0"), dead=parse_version("saas~12.5")),
            Inherit(model="account.move", born=parse_version("saas~12.4"), dead=None),
            Inherit(model="account.payment", born=parse_version("11.0"), dead=None),
        ],
        "mail.activity.mixin": [
            Inherit(model="account.asset", born=parse_version("saas~12.3"), dead=None),
            Inherit(model="account.asset.asset", born=parse_version("saas~12.1"), dead=parse_version("saas~12.3")),
            Inherit(model="account.invoice", born=parse_version("10.saas~14"), dead=parse_version("saas~12.4")),
            Inherit(model="account.journal", born=parse_version("saas~12.2"), dead=None),
            Inherit(model="account.move", born=parse_version("saas~12.2"), dead=None),
            Inherit(model="account.payment", born=parse_version("saas~12.1"), dead=None),
            Inherit(model="approval.request", born=parse_version("saas~12.2"), dead=None),
            Inherit(model="crm.lead", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="crossovered.budget", born=parse_version("saas~12.1"), dead=None),
            Inherit(model="documents.document", born=parse_version("saas~12.1"), dead=None),
            Inherit(model="event.event", born=parse_version("saas~12.1"), dead=None),
            Inherit(model="event.registration", born=parse_version("saas~12.1"), dead=None),
            Inherit(model="event.sponsor", born=parse_version("saas~13.2"), dead=None),
            Inherit(model="event.track", born=parse_version("10.saas~15"), dead=None),
            Inherit(model="fleet.vehicle", born=parse_version("saas~11.4"), dead=None),
            Inherit(model="fleet.vehicle.log.contract", born=parse_version("saas~11.3"), dead=None),
            Inherit(model="fleet.vehicle.log.services", born=parse_version("saas~13.1"), dead=None),
            Inherit(model="helpdesk.ticket", born=parse_version("10.saas~16"), dead=None),
            Inherit(model="hr.applicant", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="hr.appraisal", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="hr.appraisal.goal", born=parse_version("saas~13.4"), dead=None),
            Inherit(model="hr.contract", born=parse_version("saas~11.4"), dead=None),
            Inherit(model="hr.employee", born=parse_version("saas~11.1"), dead=None),
            Inherit(model="hr.expense", born=parse_version("saas~11.3"), dead=None),
            Inherit(model="hr.expense.sheet", born=parse_version("saas~11.3"), dead=None),
            Inherit(model="hr.leave", born=parse_version("saas~11.3"), dead=None),
            Inherit(model="hr.leave.allocation", born=parse_version("saas~11.3"), dead=None),
            Inherit(model="hr.payslip", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="hr.referral.reward", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="ir.attachment", born=parse_version("saas~11.5"), dead=parse_version("saas~12.1")),
            Inherit(model="l10n_uk.vat.obligation", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="lunch.supplier", born=parse_version("saas~12.2"), dead=None),
            Inherit(model="mailing.mailing", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="maintenance.equipment", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="maintenance.request", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="mrp.eco", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="mrp.production", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="mrp.repair", born=parse_version("10.saas~14"), dead=parse_version("saas~11.2")),
            Inherit(model="mrp.unbuild", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="mrp.workorder", born=parse_version("saas~12.1"), dead=None),
            Inherit(model="note.note", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="pos.session", born=parse_version("saas~12.3"), dead=None),
            Inherit(model="product.product", born=parse_version("10.saas~18"), dead=None),
            Inherit(model="product.template", born=parse_version("10.saas~18"), dead=None),
            Inherit(model="project.issue", born=parse_version("10.saas~14"), dead=parse_version("10.saas~18")),
            Inherit(model="project.task", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="purchase.order", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="purchase.requisition", born=parse_version("saas~12.1"), dead=None),
            Inherit(model="quality.alert", born=parse_version("saas~12.1"), dead=None),
            Inherit(model="quality.check", born=parse_version("saas~13.3"), dead=None),
            Inherit(model="repair.order", born=parse_version("saas~11.2"), dead=None),
            Inherit(model="res.partner", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="sale.order", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="sale.subscription", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="sdd.mandate", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="sign.request", born=parse_version("saas~11.5"), dead=None),
            Inherit(model="slide.channel", born=parse_version("saas~13.4"), dead=None),
            Inherit(model="social.post", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="stock.landed.cost", born=parse_version("saas~12.1"), dead=None),
            Inherit(model="stock.picking", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="stock.picking.batch", born=parse_version("saas~12.1"), dead=None),
            Inherit(model="stock.production.lot", born=parse_version("saas~11.5"), dead=None),
            Inherit(model="survey.survey", born=parse_version("10.saas~14"), dead=None),
        ],
        "mail.address.mixin": [
            Inherit(model="mail.blacklist.mixin", born=parse_version("saas~12.1"), dead=parse_version("saas~12.4")),
            Inherit(model="mail.thread.blacklist", born=parse_version("saas~12.4"), dead=parse_version("saas~13.3")),
        ],
        "mail.alias": [
            Inherit(model="crm.case.section", born=parse_version("7.0"), dead=parse_version("7.saas~5")),
            Inherit(model="hr.equipment.category", born=parse_version("9.0"), dead=parse_version("9.saas~12")),
            Inherit(model="hr.job", born=parse_version("7.0"), dead=parse_version("9.saas~10")),
            Inherit(model="mail.alias.mixin", born=parse_version("9.saas~10"), dead=None),
            Inherit(model="mail.channel", born=parse_version("9.0"), dead=parse_version("10.saas~16")),
            Inherit(model="mail.group", born=parse_version("7.0"), dead=parse_version("9.0")),
            Inherit(model="project.project", born=parse_version("7.0"), dead=parse_version("9.saas~10")),
            Inherit(model="res.users", born=parse_version("7.0"), dead=parse_version("9.saas~10")),
        ],
        "mail.alias.mixin": [
            Inherit(model="crm.team", born=parse_version("9.saas~10"), dead=None),
            Inherit(model="documents.share", born=parse_version("saas~11.5"), dead=None),
            Inherit(model="helpdesk.team", born=parse_version("9.saas~13"), dead=None),
            Inherit(model="hr.job", born=parse_version("9.saas~10"), dead=None),
            Inherit(model="mail.channel", born=parse_version("10.saas~16"), dead=None),
            Inherit(model="maintenance.equipment.category", born=parse_version("9.saas~12"), dead=None),
            Inherit(model="mrp.eco.type", born=parse_version("9.saas~12"), dead=None),
            Inherit(model="project.project", born=parse_version("9.saas~10"), dead=None),
            Inherit(model="quality.alert.team", born=parse_version("9.saas~12"), dead=None),
            Inherit(model="res.users", born=parse_version("9.saas~10"), dead=parse_version("9.saas~13")),
        ],
        "mail.blacklist.mixin": [
            Inherit(model="crm.lead", born=parse_version("saas~11.5"), dead=parse_version("saas~12.4")),
            Inherit(model="mail.channel.partner", born=parse_version("saas~11.5"), dead=parse_version("saas~12.1")),
            Inherit(
                model="mail.mass_mailing.contact", born=parse_version("saas~11.5"), dead=parse_version("saas~12.4")
            ),
            Inherit(model="res.partner", born=parse_version("saas~11.5"), dead=parse_version("saas~12.4")),
        ],
        "mail.compose.message": [
            Inherit(model="account.invoice.send", born=parse_version("saas~11.5"), dead=None),
            Inherit(model="crm.lead.forward.to.partner", born=parse_version("7.0"), dead=parse_version("7.saas~2")),
            Inherit(
                model="survey.mail.compose.message", born=parse_version("7.saas~4"), dead=parse_version("saas~12.1")
            ),
        ],
        "mail.message": [
            Inherit(model="mail.compose.message", born=parse_version("7.0"), dead=parse_version("saas~12.4")),
            Inherit(model="mail.mail", born=parse_version("7.0"), dead=None),
        ],
        "mail.message.subtype": [
            Inherit(model="crm.activity", born=parse_version("9.0"), dead=parse_version("10.saas~14"))
        ],
        "mail.render.mixin": [
            Inherit(model="mail.template", born=parse_version("saas~13.1"), dead=None),
            Inherit(model="mailing.mailing", born=parse_version("saas~13.1"), dead=None),
            Inherit(model="sms.template", born=parse_version("saas~13.1"), dead=None),
        ],
        "mail.template": [
            Inherit(model="email_template.preview", born=parse_version("8.saas~6"), dead=parse_version("saas~13.1"))
        ],
        "mail.thread": [
            Inherit(model="account.analytic.account", born=parse_version("7.0"), dead=None),
            Inherit(model="account.asset", born=parse_version("saas~12.3"), dead=None),
            Inherit(model="account.asset.asset", born=parse_version("8.saas~6"), dead=parse_version("saas~12.3")),
            Inherit(model="account.bank.statement", born=parse_version("7.0"), dead=None),
            Inherit(model="account.invoice", born=parse_version("7.0"), dead=parse_version("saas~12.4")),
            Inherit(model="account.journal", born=parse_version("saas~12.2"), dead=None),
            Inherit(model="account.move", born=parse_version("10.saas~14"), dead=parse_version("10.saas~17")),
            Inherit(model="account.move", born=parse_version("saas~12.2"), dead=None),
            Inherit(model="account.online.provider", born=parse_version("9.saas~13"), dead=None),
            Inherit(model="account.payment", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="account.voucher", born=parse_version("7.0"), dead=parse_version("saas~12.4")),
            Inherit(model="approval.request", born=parse_version("saas~12.2"), dead=None),
            Inherit(model="blog.blog", born=parse_version("7.saas~3"), dead=None),
            Inherit(model="blog.post", born=parse_version("7.saas~3"), dead=None),
            Inherit(model="calendar.appointment.type", born=parse_version("10.saas~16"), dead=None),
            Inherit(model="calendar.event", born=parse_version("7.saas~3"), dead=None),
            Inherit(model="consolidation.period", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="crm.case.section", born=parse_version("7.0"), dead=parse_version("8.saas~6")),
            Inherit(model="crm.claim", born=parse_version("7.saas~2"), dead=parse_version("9.saas~10")),
            Inherit(model="crm.helpdesk", born=parse_version("7.saas~2"), dead=parse_version("9.0")),
            Inherit(model="crm.lead", born=parse_version("10.saas~14"), dead=parse_version("saas~12.3")),
            Inherit(model="crm.meeting", born=parse_version("7.saas~2"), dead=parse_version("8.0")),
            Inherit(model="crm.phonecall", born=parse_version("7.saas~2"), dead=parse_version("9.0")),
            Inherit(model="crm.team", born=parse_version("8.saas~6"), dead=None),
            Inherit(model="crossovered.budget", born=parse_version("9.0"), dead=None),
            Inherit(model="documents.document", born=parse_version("saas~12.1"), dead=parse_version("saas~12.3")),
            Inherit(model="documents.share", born=parse_version("saas~11.5"), dead=None),
            Inherit(model="event.event", born=parse_version("7.0"), dead=None),
            Inherit(model="event.registration", born=parse_version("7.0"), dead=None),
            Inherit(model="event.sponsor", born=parse_version("saas~13.2"), dead=None),
            Inherit(model="event.track", born=parse_version("7.saas~3"), dead=None),
            Inherit(model="fleet.vehicle", born=parse_version("7.0"), dead=None),
            Inherit(model="fleet.vehicle.log.contract", born=parse_version("10.saas~18"), dead=None),
            Inherit(model="fleet.vehicle.log.services", born=parse_version("saas~13.1"), dead=None),
            Inherit(model="forum.forum", born=parse_version("7.saas~5"), dead=None),
            Inherit(model="forum.post", born=parse_version("7.saas~4"), dead=None),
            Inherit(model="forum.tag", born=parse_version("9.saas~8"), dead=None),
            Inherit(model="gamification.badge", born=parse_version("7.saas~3"), dead=None),
            Inherit(model="gamification.challenge", born=parse_version("7.saas~3"), dead=None),
            Inherit(model="gamification.goal", born=parse_version("7.saas~3"), dead=parse_version("7.saas~4")),
            Inherit(model="helpdesk.team", born=parse_version("9.saas~13"), dead=None),
            Inherit(model="helpdesk.ticket", born=parse_version("9.saas~13"), dead=parse_version("saas~12.3")),
            Inherit(model="hr.applicant", born=parse_version("7.saas~2"), dead=parse_version("saas~12.3")),
            Inherit(model="hr.appraisal", born=parse_version("9.0"), dead=None),
            Inherit(model="hr.appraisal.goal", born=parse_version("saas~13.4"), dead=None),
            Inherit(model="hr.contract", born=parse_version("8.saas~6"), dead=None),
            Inherit(model="hr.department", born=parse_version("8.saas~6"), dead=None),
            Inherit(model="hr.employee", born=parse_version("7.saas~1"), dead=None),
            Inherit(model="hr.equipment", born=parse_version("9.0"), dead=parse_version("9.saas~12")),
            Inherit(model="hr.equipment.category", born=parse_version("9.0"), dead=parse_version("9.saas~12")),
            Inherit(model="hr.equipment.request", born=parse_version("9.0"), dead=parse_version("9.saas~12")),
            Inherit(model="hr.evaluation.interview", born=parse_version("7.0"), dead=parse_version("9.0")),
            Inherit(model="hr.expense", born=parse_version("9.0"), dead=None),
            Inherit(model="hr.expense.expense", born=parse_version("7.0"), dead=parse_version("9.0")),
            Inherit(model="hr.expense.sheet", born=parse_version("9.saas~12"), dead=None),
            Inherit(model="hr.holidays", born=parse_version("7.0"), dead=parse_version("saas~11.2")),
            Inherit(model="hr.job", born=parse_version("7.0"), dead=None),
            Inherit(model="hr.leave", born=parse_version("saas~11.2"), dead=None),
            Inherit(model="hr.leave.allocation", born=parse_version("saas~11.2"), dead=None),
            Inherit(model="hr.referral.reward", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="hr_evaluation.evaluation", born=parse_version("7.0"), dead=parse_version("9.0")),
            Inherit(model="hr_timesheet_sheet.sheet", born=parse_version("7.0"), dead=parse_version("10.saas~17")),
            Inherit(model="idea.idea", born=parse_version("7.0"), dead=parse_version("7.saas~2")),
            Inherit(model="ir.attachment", born=parse_version("saas~11.5"), dead=parse_version("saas~12.1")),
            Inherit(model="l10n_uk.vat.obligation", born=parse_version("10.0"), dead=None),
            Inherit(model="lunch.supplier", born=parse_version("saas~12.2"), dead=None),
            Inherit(model="mail.blacklist", born=parse_version("saas~11.5"), dead=None),
            Inherit(model="mail.channel", born=parse_version("9.0"), dead=None),
            Inherit(model="mail.channel.github", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="mail.group", born=parse_version("7.0"), dead=parse_version("9.0")),
            Inherit(model="mail.mass_mailing.contact", born=parse_version("8.0"), dead=parse_version("saas~12.4")),
            Inherit(model="mail.thread.blacklist", born=parse_version("saas~12.4"), dead=None),
            Inherit(model="mail.thread.cc", born=parse_version("saas~12.3"), dead=None),
            Inherit(model="mail.thread.phone", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="mailing.mailing", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="maintenance.equipment", born=parse_version("9.saas~12"), dead=None),
            Inherit(model="maintenance.equipment.category", born=parse_version("9.saas~12"), dead=None),
            Inherit(model="maintenance.request", born=parse_version("9.saas~12"), dead=parse_version("saas~12.3")),
            Inherit(model="mrp.bom", born=parse_version("7.0"), dead=None),
            Inherit(model="mrp.eco", born=parse_version("9.saas~12"), dead=parse_version("saas~12.3")),
            Inherit(model="mrp.eco.type", born=parse_version("9.saas~12"), dead=None),
            Inherit(model="mrp.production", born=parse_version("7.0"), dead=None),
            Inherit(model="mrp.production.workcenter.line", born=parse_version("7.0"), dead=parse_version("9.saas~12")),
            Inherit(model="mrp.repair", born=parse_version("7.0"), dead=parse_version("saas~11.2")),
            Inherit(model="mrp.unbuild", born=parse_version("9.saas~12"), dead=None),
            Inherit(model="mrp.workorder", born=parse_version("9.saas~12"), dead=None),
            Inherit(model="note.note", born=parse_version("7.0"), dead=None),
            Inherit(model="online.account", born=parse_version("9.0"), dead=parse_version("9.saas~13")),
            Inherit(model="payment.transaction", born=parse_version("7.saas~3"), dead=parse_version("9.0")),
            Inherit(model="phone.blacklist", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="pos.session", born=parse_version("saas~12.3"), dead=None),
            Inherit(model="procurement.order", born=parse_version("7.0"), dead=parse_version("10.saas~18")),
            Inherit(model="product.product", born=parse_version("7.0"), dead=None),
            Inherit(model="product.template", born=parse_version("7.saas~3"), dead=None),
            Inherit(model="project.issue", born=parse_version("7.saas~2"), dead=parse_version("10.saas~18")),
            Inherit(model="project.project", born=parse_version("7.0"), dead=None),
            Inherit(model="project.task", born=parse_version("7.saas~2"), dead=parse_version("saas~12.3")),
            Inherit(model="purchase.order", born=parse_version("7.0"), dead=None),
            Inherit(model="purchase.requisition", born=parse_version("7.0"), dead=None),
            Inherit(model="quality.alert", born=parse_version("9.saas~12"), dead=parse_version("saas~12.3")),
            Inherit(model="quality.alert.team", born=parse_version("9.saas~12"), dead=None),
            Inherit(model="quality.check", born=parse_version("9.saas~12"), dead=None),
            Inherit(model="quality.point", born=parse_version("9.saas~12"), dead=None),
            Inherit(model="repair.order", born=parse_version("saas~11.2"), dead=None),
            Inherit(model="res.partner", born=parse_version("7.0"), dead=parse_version("saas~12.4")),
            Inherit(model="sale.order", born=parse_version("7.0"), dead=None),
            Inherit(model="sale.subscription", born=parse_version("9.0"), dead=None),
            Inherit(model="sale.subscription.template", born=parse_version("9.saas~13"), dead=None),
            Inherit(model="sdd.mandate", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="sign.request", born=parse_version("saas~11.5"), dead=None),
            Inherit(model="signature.request", born=parse_version("8.saas~6"), dead=parse_version("saas~11.5")),
            Inherit(model="slide.channel", born=parse_version("8.saas~6"), dead=None),
            Inherit(model="slide.slide", born=parse_version("8.saas~6"), dead=None),
            Inherit(model="social.media", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="social.post", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="stock.landed.cost", born=parse_version("7.saas~5"), dead=None),
            Inherit(model="stock.picking", born=parse_version("7.0"), dead=None),
            Inherit(model="stock.picking.batch", born=parse_version("10.saas~17"), dead=None),
            Inherit(model="stock.picking.wave", born=parse_version("9.0"), dead=parse_version("10.saas~17")),
            Inherit(model="stock.production.lot", born=parse_version("7.saas~5"), dead=None),
            Inherit(model="stock.scrap", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="survey.survey", born=parse_version("7.saas~4"), dead=None),
            Inherit(model="team.user", born=parse_version("9.saas~13"), dead=None),
            Inherit(model="website.crm.score", born=parse_version("9.saas~13"), dead=None),
            Inherit(
                model="website_version.experiment", born=parse_version("8.saas~6"), dead=parse_version("saas~11.5")
            ),
        ],
        "mail.thread.blacklist": [
            Inherit(model="crm.lead", born=parse_version("saas~12.4"), dead=None),
            Inherit(
                model="mail.mass_mailing.contact", born=parse_version("saas~12.4"), dead=parse_version("saas~12.5")
            ),
            Inherit(model="mailing.contact", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="res.partner", born=parse_version("saas~12.4"), dead=None),
        ],
        "mail.thread.cc": [
            Inherit(model="crm.lead", born=parse_version("saas~12.3"), dead=None),
            Inherit(model="documents.document", born=parse_version("saas~12.3"), dead=None),
            Inherit(model="helpdesk.ticket", born=parse_version("saas~12.3"), dead=None),
            Inherit(model="hr.applicant", born=parse_version("saas~12.3"), dead=None),
            Inherit(model="hr.payslip", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="maintenance.request", born=parse_version("saas~12.3"), dead=None),
            Inherit(model="mrp.eco", born=parse_version("saas~12.3"), dead=None),
            Inherit(model="project.task", born=parse_version("saas~12.3"), dead=None),
            Inherit(model="quality.alert", born=parse_version("saas~12.3"), dead=None),
        ],
        "mail.thread.phone": [
            Inherit(model="crm.lead", born=parse_version("saas~13.3"), dead=None),
            Inherit(model="mailing.contact", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="res.partner", born=parse_version("saas~12.5"), dead=None),
        ],
        "mrp.abstract.workorder": [
            Inherit(model="mrp.product.produce", born=parse_version("saas~12.2"), dead=parse_version("saas~13.4")),
            Inherit(model="mrp.workorder", born=parse_version("saas~12.2"), dead=parse_version("saas~13.4")),
        ],
        "mrp.abstract.workorder.line": [
            Inherit(model="mrp.product.produce.line", born=parse_version("saas~12.2"), dead=parse_version("saas~13.4")),
            Inherit(model="mrp.workorder.line", born=parse_version("saas~12.2"), dead=parse_version("saas~13.4")),
        ],
        "pad.common": [
            Inherit(model="note.note", born=parse_version("7.0"), dead=None),
            Inherit(model="project.task", born=parse_version("7.0"), dead=None),
        ],
        "payment.acquirer.onboarding.wizard": [
            Inherit(model="sale.payment.acquirer.onboarding.wizard", born=parse_version("saas~11.5"), dead=None),
            Inherit(
                model="website.sale.payment.acquirer.onboarding.wizard", born=parse_version("saas~11.5"), dead=None
            ),
        ],
        "phone.validation.mixin": [
            Inherit(model="crm.lead", born=parse_version("10.saas~16"), dead=None),
            Inherit(model="res.partner", born=parse_version("10.saas~16"), dead=None),
        ],
        "portal.mixin": [
            Inherit(model="account.invoice", born=parse_version("10.saas~18"), dead=parse_version("saas~12.4")),
            Inherit(model="account.move", born=parse_version("saas~12.4"), dead=None),
            Inherit(model="helpdesk.ticket", born=parse_version("10.saas~18"), dead=None),
            Inherit(model="project.project", born=parse_version("10.saas~18"), dead=None),
            Inherit(model="project.task", born=parse_version("10.saas~18"), dead=None),
            Inherit(model="purchase.order", born=parse_version("saas~11.5"), dead=None),
            Inherit(model="sale.order", born=parse_version("10.saas~18"), dead=None),
            Inherit(model="sign.request.item", born=parse_version("saas~13.2"), dead=None),
        ],
        "pos.order.line": [Inherit(model="pos.order_line_pro_forma", born=parse_version("9.0"), dead=None)],
        "print.mixin": [
            Inherit(model="account.invoice", born=parse_version("9.0"), dead=parse_version("saas~11.5")),
            Inherit(model="sale.order", born=parse_version("9.0"), dead=parse_version("saas~11.5")),
        ],
        "product.product": [
            Inherit(model="delivery.carrier", born=parse_version("9.0"), dead=parse_version("10.saas~18"))
        ],
        "product.template": [Inherit(model="product.product", born=parse_version("7.0"), dead=None)],
        "project.task.history": [
            Inherit(model="project.task.history.cumulative", born=parse_version("7.0"), dead=parse_version("9.saas~13"))
        ],
        "rating.mixin": [
            Inherit(model="helpdesk.ticket", born=parse_version("9.saas~13"), dead=None),
            Inherit(model="im_chat.session", born=parse_version("8.saas~6"), dead=parse_version("9.0")),
            Inherit(model="mail.channel", born=parse_version("9.0"), dead=None),
            Inherit(model="product.template", born=parse_version("9.0"), dead=None),
            Inherit(model="project.issue", born=parse_version("8.saas~6"), dead=parse_version("10.saas~18")),
            Inherit(model="project.task", born=parse_version("8.saas~6"), dead=None),
            Inherit(model="sale.subscription", born=parse_version("saas~11.5"), dead=None),
            Inherit(model="slide.channel", born=parse_version("saas~12.2"), dead=None),
            Inherit(model="slide.slide", born=parse_version("saas~12.2"), dead=parse_version("saas~12.5")),
        ],
        "rating.parent.mixin": [
            Inherit(model="helpdesk.team", born=parse_version("saas~12.1"), dead=None),
            Inherit(model="im_livechat.channel", born=parse_version("saas~12.1"), dead=None),
            Inherit(model="project.project", born=parse_version("saas~12.1"), dead=None),
        ],
        "report.abstract_report": [
            Inherit(
                model="report.account.report_agedpartnerbalance",
                born=parse_version("7.saas~4"),
                dead=parse_version("9.0"),
            ),
            Inherit(
                model="report.account.report_analyticbalance", born=parse_version("7.saas~4"), dead=parse_version("9.0")
            ),
            Inherit(
                model="report.account.report_analyticcostledger",
                born=parse_version("7.saas~4"),
                dead=parse_version("9.0"),
            ),
            Inherit(
                model="report.account.report_analyticcostledgerquantity",
                born=parse_version("7.saas~4"),
                dead=parse_version("9.0"),
            ),
            Inherit(
                model="report.account.report_analyticjournal", born=parse_version("7.saas~4"), dead=parse_version("9.0")
            ),
            Inherit(
                model="report.account.report_centraljournal", born=parse_version("7.saas~4"), dead=parse_version("9.0")
            ),
            Inherit(model="report.account.report_financial", born=parse_version("7.saas~4"), dead=parse_version("9.0")),
            Inherit(
                model="report.account.report_generaljournal", born=parse_version("7.saas~4"), dead=parse_version("9.0")
            ),
            Inherit(
                model="report.account.report_generalledger", born=parse_version("7.saas~4"), dead=parse_version("9.0")
            ),
            Inherit(
                model="report.account.report_invertedanalyticbalance",
                born=parse_version("7.saas~4"),
                dead=parse_version("9.0"),
            ),
            Inherit(model="report.account.report_journal", born=parse_version("7.saas~4"), dead=parse_version("9.0")),
            Inherit(model="report.account.report_overdue", born=parse_version("7.saas~4"), dead=parse_version("9.0")),
            Inherit(
                model="report.account.report_partnerbalance", born=parse_version("7.saas~4"), dead=parse_version("9.0")
            ),
            Inherit(
                model="report.account.report_partnerledger", born=parse_version("7.saas~4"), dead=parse_version("9.0")
            ),
            Inherit(
                model="report.account.report_partnerledgerother",
                born=parse_version("7.saas~4"),
                dead=parse_version("9.0"),
            ),
            Inherit(
                model="report.account.report_salepurchasejournal",
                born=parse_version("7.saas~4"),
                dead=parse_version("9.0"),
            ),
            Inherit(
                model="report.account.report_trialbalance", born=parse_version("7.saas~4"), dead=parse_version("9.0")
            ),
            Inherit(model="report.account.report_vat", born=parse_version("7.saas~4"), dead=parse_version("9.0")),
            Inherit(
                model="report.account_analytic_plans.report_crossoveredanalyticplans",
                born=parse_version("7.saas~4"),
                dead=parse_version("9.0"),
            ),
            Inherit(
                model="report.account_bank_statement_extensions.report_bankstatementbalance",
                born=parse_version("7.saas~4"),
                dead=parse_version("9.0"),
            ),
            Inherit(
                model="report.account_batch_deposit.print_batch_deposit",
                born=parse_version("9.0"),
                dead=parse_version("9.saas~13"),
            ),
            Inherit(
                model="report.account_budget.report_analyticaccountbudget",
                born=parse_version("7.saas~4"),
                dead=parse_version("9.saas~13"),
            ),
            Inherit(
                model="report.account_budget.report_budget",
                born=parse_version("7.saas~4"),
                dead=parse_version("9.saas~13"),
            ),
            Inherit(
                model="report.account_budget.report_crossoveredbudget",
                born=parse_version("7.saas~4"),
                dead=parse_version("9.saas~13"),
            ),
            Inherit(
                model="report.account_check_writing.report_check",
                born=parse_version("7.saas~4"),
                dead=parse_version("9.0"),
            ),
            Inherit(
                model="report.account_followup.report_followup",
                born=parse_version("7.saas~4"),
                dead=parse_version("9.0"),
            ),
            Inherit(
                model="report.account_payment.report_paymentorder",
                born=parse_version("7.saas~4"),
                dead=parse_version("9.0"),
            ),
            Inherit(
                model="report.hr_attendance.report_attendanceerrors",
                born=parse_version("7.saas~4"),
                dead=parse_version("9.saas~13"),
            ),
            Inherit(
                model="report.hr_expense.report_expense", born=parse_version("9.0"), dead=parse_version("9.saas~12")
            ),
            Inherit(
                model="report.hr_payroll.report_contributionregister",
                born=parse_version("7.saas~4"),
                dead=parse_version("9.saas~13"),
            ),
            Inherit(
                model="report.hr_payroll.report_payslip",
                born=parse_version("7.saas~4"),
                dead=parse_version("9.saas~13"),
            ),
            Inherit(
                model="report.hr_payroll.report_payslipdetails",
                born=parse_version("7.saas~4"),
                dead=parse_version("9.saas~13"),
            ),
            Inherit(
                model="report.hr_timesheet_invoice.report_analyticprofit",
                born=parse_version("7.saas~4"),
                dead=parse_version("9.0"),
            ),
            Inherit(
                model="report.l10n_be.report_l10nvatintraprint",
                born=parse_version("7.saas~5"),
                dead=parse_version("9.0"),
            ),
            Inherit(
                model="report.l10n_be.report_l10nvatpartnerlisting",
                born=parse_version("7.saas~5"),
                dead=parse_version("9.0"),
            ),
            Inherit(
                model="report.l10n_fr.report_l10nfrbilan", born=parse_version("7.saas~5"), dead=parse_version("9.0")
            ),
            Inherit(
                model="report.l10n_fr.report_l10nfrresultat", born=parse_version("7.saas~5"), dead=parse_version("9.0")
            ),
            Inherit(
                model="report.l10n_fr_hr_payroll.report_l10nfrfichepaye",
                born=parse_version("7.saas~5"),
                dead=parse_version("9.saas~13"),
            ),
            Inherit(
                model="report.l10n_in_hr_payroll.report_hrsalarybymonth",
                born=parse_version("7.saas~5"),
                dead=parse_version("9.saas~13"),
            ),
            Inherit(
                model="report.l10n_in_hr_payroll.report_hryearlysalary",
                born=parse_version("7.saas~5"),
                dead=parse_version("9.saas~13"),
            ),
            Inherit(
                model="report.l10n_in_hr_payroll.report_payrolladvice",
                born=parse_version("7.saas~5"),
                dead=parse_version("9.saas~13"),
            ),
            Inherit(
                model="report.l10n_in_hr_payroll.report_payslipdetails",
                born=parse_version("7.saas~5"),
                dead=parse_version("9.saas~13"),
            ),
            Inherit(
                model="report.l10n_us_check_printing.print_check_bottom",
                born=parse_version("9.0"),
                dead=parse_version("10.saas~16"),
            ),
            Inherit(
                model="report.l10n_us_check_printing.print_check_middle",
                born=parse_version("9.0"),
                dead=parse_version("10.saas~16"),
            ),
            Inherit(
                model="report.l10n_us_check_printing.print_check_top",
                born=parse_version("9.0"),
                dead=parse_version("10.saas~16"),
            ),
            Inherit(model="report.lunch.report_lunchorder", born=parse_version("7.saas~4"), dead=parse_version("9.0")),
            Inherit(
                model="report.mrp.report_mrpbomstructure",
                born=parse_version("7.saas~4"),
                dead=parse_version("9.saas~13"),
            ),
            Inherit(
                model="report.point_of_sale.report_detailsofsales",
                born=parse_version("7.saas~5"),
                dead=parse_version("9.saas~10"),
            ),
            Inherit(
                model="report.point_of_sale.report_payment",
                born=parse_version("7.saas~5"),
                dead=parse_version("9.saas~10"),
            ),
            Inherit(
                model="report.point_of_sale.report_receipt",
                born=parse_version("7.saas~5"),
                dead=parse_version("9.saas~8"),
            ),
            Inherit(
                model="report.point_of_sale.report_saleslines",
                born=parse_version("7.saas~5"),
                dead=parse_version("9.saas~10"),
            ),
            Inherit(
                model="report.point_of_sale.report_statement",
                born=parse_version("7.saas~5"),
                dead=parse_version("9.saas~12"),
            ),
            Inherit(
                model="report.point_of_sale.report_usersproduct",
                born=parse_version("7.saas~5"),
                dead=parse_version("9.saas~12"),
            ),
            Inherit(
                model="report.product.report_pricelist", born=parse_version("7.saas~5"), dead=parse_version("9.saas~13")
            ),
        ],
        "report.account.report_invoice": [
            Inherit(model="report.account.report_invoice_with_payments", born=parse_version("saas~13.3"), dead=None)
        ],
        "report.hr_payroll.report_payslipdetails": [
            Inherit(
                model="report.l10n_in_hr_payroll.report_payslipdetails",
                born=parse_version("9.saas~13"),
                dead=parse_version("saas~12.1"),
            )
        ],
        "report.project.task.user": [
            Inherit(model="report.project.task.user.fsm", born=parse_version("saas~12.5"), dead=None)
        ],
        "res.alarm": [Inherit(model="calendar.alarm", born=parse_version("7.0"), dead=parse_version("7.saas~3"))],
        "res.config": [
            Inherit(model="base.setup.terminology", born=parse_version("7.0"), dead=parse_version("9.saas~11")),
            Inherit(model="document.configuration", born=parse_version("7.0"), dead=parse_version("9.0")),
            Inherit(model="document.ftp.configuration", born=parse_version("7.0"), dead=parse_version("7.saas~4")),
            Inherit(model="ir.actions.configuration.wizard", born=parse_version("7.0"), dead=parse_version("7.saas~3")),
            Inherit(model="wizard.multi.charts.accounts", born=parse_version("7.0"), dead=parse_version("saas~11.5")),
        ],
        "res.config.installer": [
            Inherit(model="account.installer", born=parse_version("7.0"), dead=parse_version("9.0")),
            Inherit(model="account.sequence.installer", born=parse_version("7.0"), dead=parse_version("9.0")),
            Inherit(model="base_report_designer.installer", born=parse_version("7.0"), dead=parse_version("8.saas~6")),
            Inherit(model="outlook.installer", born=parse_version("7.0"), dead=parse_version("8.0")),
            Inherit(model="plugin_thunderbird.installer", born=parse_version("7.0"), dead=parse_version("8.0")),
        ],
        "res.config.settings": [
            Inherit(model="account.config.settings", born=parse_version("7.0"), dead=parse_version("10.saas~18")),
            Inherit(
                model="attendance.config.settings", born=parse_version("10.saas~15"), dead=parse_version("10.saas~18")
            ),
            Inherit(model="base.config.settings", born=parse_version("7.0"), dead=parse_version("10.saas~18")),
            Inherit(model="event.config.settings", born=parse_version("9.0"), dead=parse_version("10.saas~18")),
            Inherit(model="fleet.config.settings", born=parse_version("10.saas~16"), dead=parse_version("10.saas~18")),
            Inherit(model="hr.config.settings", born=parse_version("7.0"), dead=parse_version("9.0")),
            Inherit(model="hr.config.settings", born=parse_version("10.saas~15"), dead=parse_version("10.saas~18")),
            Inherit(model="hr.equipment.config.settings", born=parse_version("9.0"), dead=parse_version("9.saas~12")),
            Inherit(
                model="hr.expense.config.settings", born=parse_version("9.saas~12"), dead=parse_version("10.saas~18")
            ),
            Inherit(model="hr.payroll.config.settings", born=parse_version("9.0"), dead=parse_version("10.saas~18")),
            Inherit(
                model="hr.recruitment.config.settings", born=parse_version("9.0"), dead=parse_version("10.saas~18")
            ),
            Inherit(model="knowledge.config.settings", born=parse_version("7.0"), dead=parse_version("9.0")),
            Inherit(model="marketing.config.settings", born=parse_version("7.0"), dead=parse_version("9.saas~7")),
            Inherit(model="mass.mailing.config.settings", born=parse_version("9.0"), dead=parse_version("10.saas~18")),
            Inherit(model="mrp.config.settings", born=parse_version("7.0"), dead=parse_version("10.saas~18")),
            Inherit(model="pos.config.settings", born=parse_version("9.0"), dead=parse_version("10.saas~18")),
            Inherit(model="project.config.settings", born=parse_version("7.0"), dead=parse_version("10.saas~18")),
            Inherit(model="purchase.config.settings", born=parse_version("7.0"), dead=parse_version("10.saas~18")),
            Inherit(model="sale.config.settings", born=parse_version("7.0"), dead=parse_version("10.saas~18")),
            Inherit(
                model="sale.subscription.config.settings",
                born=parse_version("10.saas~17"),
                dead=parse_version("10.saas~18"),
            ),
            Inherit(model="stock.config.settings", born=parse_version("7.0"), dead=parse_version("10.saas~18")),
            Inherit(model="website.config.settings", born=parse_version("7.saas~3"), dead=parse_version("10.saas~18")),
        ],
        "res.partner": [Inherit(model="res.users", born=parse_version("7.0"), dead=None)],
        "res.partner.bank": [
            Inherit(model="account.setup.bank.manual.config", born=parse_version("saas~11.4"), dead=None)
        ],
        "resource.mixin": [
            Inherit(model="hr.employee", born=parse_version("10.saas~15"), dead=None),
            Inherit(model="mrp.workcenter", born=parse_version("10.saas~15"), dead=None),
        ],
        "resource.resource": [
            Inherit(model="hr.employee", born=parse_version("7.0"), dead=parse_version("10.saas~15")),
            Inherit(model="mrp.workcenter", born=parse_version("7.0"), dead=parse_version("10.saas~15")),
        ],
        "sale.coupon.reward": [
            Inherit(model="sale.coupon.program", born=parse_version("10.saas~14"), dead=parse_version("saas~13.4"))
        ],
        "sale.coupon.rule": [
            Inherit(model="sale.coupon.program", born=parse_version("10.saas~14"), dead=parse_version("saas~13.4"))
        ],
        "sale.rental.report.abstract": [
            Inherit(model="sale.rental.report", born=parse_version("saas~12.4"), dead=parse_version("saas~12.5")),
            Inherit(model="sale.rental.schedule", born=parse_version("saas~12.4"), dead=parse_version("saas~12.5")),
        ],
        "sale.subscription.line": [
            Inherit(model="sale.subscription.line.option", born=parse_version("9.0"), dead=parse_version("9.saas~13"))
        ],
        "sale.subscription.line.option": [
            Inherit(model="sale.subscription.wizard.option", born=parse_version("9.0"), dead=parse_version("9.saas~13"))
        ],
        "sale.subscription.template.line": [
            Inherit(
                model="sale.subscription.template.option",
                born=parse_version("9.saas~13"),
                dead=parse_version("10.saas~17"),
            )
        ],
        "sale.subscription.template.option": [
            Inherit(
                model="sale.subscription.wizard.option",
                born=parse_version("9.saas~13"),
                dead=parse_version("10.saas~17"),
            )
        ],
        "sequence.mixin": [
            Inherit(model="account.bank.statement", born=parse_version("saas~13.2"), dead=None),
            Inherit(model="account.move", born=parse_version("saas~13.2"), dead=None),
        ],
        "sms.template": [
            Inherit(model="sms.template.preview", born=parse_version("saas~12.5"), dead=parse_version("saas~13.3"))
        ],
        "snailmail.confirm": [
            Inherit(model="snailmail.confirm.followup", born=parse_version("saas~13.4"), dead=None),
            Inherit(model="snailmail.confirm.invoice", born=parse_version("saas~13.4"), dead=None),
        ],
        "stock.move.consume": [
            Inherit(model="stock.move.scrap", born=parse_version("7.0"), dead=parse_version("7.saas~5"))
        ],
        "stock.move.split": [
            Inherit(model="stock.inventory.line.split", born=parse_version("7.0"), dead=parse_version("7.saas~5"))
        ],
        "stock.move.split.lines": [
            Inherit(model="stock.inventory.line.split.lines", born=parse_version("7.0"), dead=parse_version("7.saas~5"))
        ],
        "stock.partial.picking": [
            Inherit(model="stock.partial.move", born=parse_version("7.0"), dead=parse_version("7.saas~5"))
        ],
        "stock.partial.picking.line": [
            Inherit(model="stock.partial.move.line", born=parse_version("7.0"), dead=parse_version("7.saas~5"))
        ],
        "stock.picking": [
            Inherit(model="stock.picking.in", born=parse_version("7.0"), dead=parse_version("7.saas~5")),
            Inherit(model="stock.picking.out", born=parse_version("7.0"), dead=parse_version("7.saas~5")),
        ],
        "stock.warn.insufficient.qty": [
            Inherit(model="stock.warn.insufficient.qty.repair", born=parse_version("10.saas~18"), dead=None),
            Inherit(model="stock.warn.insufficient.qty.scrap", born=parse_version("10.saas~18"), dead=None),
            Inherit(model="stock.warn.insufficient.qty.unbuild", born=parse_version("10.saas~18"), dead=None),
        ],
        "studio.mixin": [
            Inherit(model="base.action.rule", born=parse_version("10.0"), dead=parse_version("10.saas~14")),
            Inherit(model="base.automation", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="ir.actions.act_window", born=parse_version("10.0"), dead=None),
            Inherit(model="ir.actions.act_window.view", born=parse_version("10.0"), dead=None),
            Inherit(model="ir.actions.report", born=parse_version("10.saas~17"), dead=None),
            Inherit(model="ir.actions.report.xml", born=parse_version("10.0"), dead=parse_version("10.saas~17")),
            Inherit(model="ir.actions.server", born=parse_version("10.0"), dead=None),
            Inherit(model="ir.filters", born=parse_version("10.0"), dead=None),
            Inherit(model="ir.model", born=parse_version("10.0"), dead=None),
            Inherit(model="ir.model.access", born=parse_version("10.0"), dead=None),
            Inherit(model="ir.model.fields", born=parse_version("10.0"), dead=None),
            Inherit(model="ir.rule", born=parse_version("10.0"), dead=None),
            Inherit(model="ir.ui.menu", born=parse_version("10.0"), dead=None),
            Inherit(model="ir.ui.view", born=parse_version("10.0"), dead=None),
            Inherit(model="mail.template", born=parse_version("10.0"), dead=None),
            Inherit(model="report.paperformat", born=parse_version("saas~12.1"), dead=None),
            Inherit(model="res.groups", born=parse_version("10.0"), dead=None),
            Inherit(model="studio.approval.rule", born=parse_version("saas~13.4"), dead=None),
        ],
        "survey.request": [
            Inherit(model="hr.evaluation.interview", born=parse_version("7.0"), dead=parse_version("7.saas~4"))
        ],
        "timer.mixin": [
            Inherit(model="account.analytic.line", born=parse_version("saas~13.2"), dead=None),
            Inherit(model="helpdesk.ticket", born=parse_version("saas~13.2"), dead=None),
            Inherit(model="project.task", born=parse_version("saas~13.2"), dead=None),
        ],
        "utm.campaign": [
            Inherit(
                model="mail.mass_mailing.campaign", born=parse_version("8.saas~6"), dead=parse_version("saas~12.5")
            ),
            Inherit(model="marketing.campaign", born=parse_version("10.saas~18"), dead=None),
        ],
        "utm.medium": [Inherit(model="social.account", born=parse_version("saas~12.5"), dead=None)],
        "utm.mixin": [
            Inherit(model="account.invoice", born=parse_version("9.saas~8"), dead=parse_version("saas~12.4")),
            Inherit(model="account.move", born=parse_version("saas~12.4"), dead=None),
            Inherit(model="crm.lead", born=parse_version("10.saas~14"), dead=None),
            Inherit(model="crm.lead.report", born=parse_version("8.saas~6"), dead=parse_version("9.0")),
            Inherit(model="crm.opportunity.report", born=parse_version("8.saas~6"), dead=parse_version("9.saas~8")),
            Inherit(model="helpdesk.ticket", born=parse_version("9.saas~13"), dead=None),
            Inherit(model="hr.applicant", born=parse_version("8.saas~6"), dead=None),
            Inherit(model="link.tracker", born=parse_version("9.0"), dead=None),
            Inherit(model="mail.mass_mailing", born=parse_version("8.saas~6"), dead=parse_version("9.saas~8")),
            Inherit(model="mail.mass_mailing.campaign", born=parse_version("8.saas~6"), dead=parse_version("9.saas~8")),
            Inherit(model="sale.order", born=parse_version("8.saas~6"), dead=None),
            Inherit(model="website.links", born=parse_version("8.saas~6"), dead=parse_version("9.0")),
        ],
        "utm.source": [
            Inherit(model="hr.recruitment.source", born=parse_version("8.saas~6"), dead=None),
            Inherit(model="mail.mass_mailing", born=parse_version("9.saas~8"), dead=parse_version("saas~12.5")),
            Inherit(model="mailing.mailing", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="marketing.activity", born=parse_version("10.saas~18"), dead=None),
        ],
        "voip.queue.mixin": [
            Inherit(model="crm.lead", born=parse_version("saas~12.1"), dead=None),
            Inherit(model="res.partner", born=parse_version("saas~12.1"), dead=None),
        ],
        "website.cover_properties.mixin": [
            Inherit(model="blog.blog", born=parse_version("saas~13.2"), dead=None),
            Inherit(model="blog.post", born=parse_version("saas~13.2"), dead=None),
            Inherit(model="event.event", born=parse_version("saas~13.2"), dead=None),
        ],
        "website.multi.mixin": [
            Inherit(model="blog.blog", born=parse_version("saas~11.5"), dead=None),
            Inherit(model="coupon.program", born=parse_version("saas~13.4"), dead=None),
            Inherit(model="forum.forum", born=parse_version("saas~11.5"), dead=None),
            Inherit(model="product.public.category", born=parse_version("saas~11.5"), dead=None),
            Inherit(model="sale.coupon.program", born=parse_version("saas~11.5"), dead=parse_version("saas~13.4")),
        ],
        "website.published.mixin": [
            Inherit(model="blog.post", born=parse_version("8.saas~6"), dead=parse_version("saas~11.5")),
            Inherit(model="calendar.appointment.type", born=parse_version("10.saas~16"), dead=None),
            Inherit(model="delivery.carrier", born=parse_version("9.saas~11"), dead=parse_version("saas~11.5")),
            Inherit(model="event.event", born=parse_version("8.saas~6"), dead=parse_version("saas~11.5")),
            Inherit(model="event.track", born=parse_version("8.saas~6"), dead=None),
            Inherit(model="gamification.badge", born=parse_version("saas~12.2"), dead=None),
            Inherit(model="helpdesk.team", born=parse_version("9.saas~13"), dead=None),
            Inherit(model="hr.employee", born=parse_version("8.saas~6"), dead=parse_version("saas~11.5")),
            Inherit(model="hr.job", born=parse_version("8.saas~6"), dead=parse_version("saas~11.5")),
            Inherit(model="im_livechat.channel", born=parse_version("8.saas~6"), dead=None),
            Inherit(model="payment.acquirer", born=parse_version("9.0"), dead=parse_version("10.saas~17")),
            Inherit(model="product.template", born=parse_version("8.saas~6"), dead=parse_version("saas~11.5")),
            Inherit(model="project.project", born=parse_version("9.0"), dead=parse_version("10.saas~18")),
            Inherit(model="project.project", born=parse_version("saas~13.4"), dead=None),
            Inherit(model="res.partner", born=parse_version("8.saas~6"), dead=parse_version("saas~12.2")),
            Inherit(model="res.partner.grade", born=parse_version("8.saas~6"), dead=None),
            Inherit(model="res.partner.tag", born=parse_version("8.saas~6"), dead=None),
            Inherit(model="slide.channel", born=parse_version("8.saas~6"), dead=parse_version("saas~11.5")),
            Inherit(model="slide.channel.tag.group", born=parse_version("saas~12.5"), dead=None),
            Inherit(model="slide.slide", born=parse_version("8.saas~6"), dead=None),
            Inherit(model="website.page", born=parse_version("10.saas~18"), dead=parse_version("saas~11.5")),
            Inherit(model="website.twitter.wall", born=parse_version("saas~11.5"), dead=None),
        ],
        "website.published.multi.mixin": [
            Inherit(model="blog.post", born=parse_version("saas~11.5"), dead=None),
            Inherit(model="delivery.carrier", born=parse_version("saas~11.5"), dead=None),
            Inherit(model="event.event", born=parse_version("saas~11.5"), dead=None),
            Inherit(model="hr.employee", born=parse_version("saas~11.5"), dead=parse_version("saas~12.5")),
            Inherit(model="hr.employee.public", born=parse_version("saas~12.4"), dead=parse_version("saas~12.5")),
            Inherit(model="hr.job", born=parse_version("saas~11.5"), dead=None),
            Inherit(model="product.template", born=parse_version("saas~11.5"), dead=None),
            Inherit(model="res.partner", born=parse_version("saas~12.2"), dead=None),
            Inherit(model="slide.channel", born=parse_version("saas~11.5"), dead=None),
            Inherit(model="website.page", born=parse_version("saas~11.5"), dead=None),
        ],
        "website.seo.metadata": [
            Inherit(model="blog.blog", born=parse_version("7.saas~3"), dead=None),
            Inherit(model="blog.post", born=parse_version("7.saas~3"), dead=None),
            Inherit(model="blog.tag", born=parse_version("7.saas~3"), dead=None),
            Inherit(model="calendar.appointment.type", born=parse_version("10.saas~16"), dead=None),
            Inherit(model="event.event", born=parse_version("7.saas~3"), dead=None),
            Inherit(model="event.track", born=parse_version("7.saas~3"), dead=None),
            Inherit(model="forum.documentation.toc", born=parse_version("7.saas~4"), dead=parse_version("saas~11.5")),
            Inherit(model="forum.forum", born=parse_version("7.saas~4"), dead=None),
            Inherit(model="forum.post", born=parse_version("7.saas~4"), dead=None),
            Inherit(model="forum.tag", born=parse_version("7.saas~4"), dead=None),
            Inherit(model="hr.job", born=parse_version("7.saas~3"), dead=None),
            Inherit(model="ir.ui.view", born=parse_version("9.0"), dead=None),
            Inherit(model="product.public.category", born=parse_version("8.saas~6"), dead=None),
            Inherit(model="product.template", born=parse_version("7.saas~3"), dead=None),
            Inherit(model="res.partner", born=parse_version("7.saas~3"), dead=None),
            Inherit(model="slide.channel", born=parse_version("8.saas~6"), dead=None),
            Inherit(model="slide.slide", born=parse_version("8.saas~6"), dead=None),
        ],
    }
)
